#!/usr/bin/env python3
"""Helpers for running Samsung Exynos AI Studio's `eais` CLI from this repo.

The real converter is Samsung's CLI. This wrapper keeps paths, model linking,
preflight checks, and conservative conversion command lines reproducible.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence

DEFAULT_CONFIG = Path("configs/whisper-large-v3-turbo-samsung.json")
DEFAULT_WORKSPACE = Path("output/eais/whisper-large-v3-turbo")
DEFAULT_MODEL = Path("output/simplified/encoder_model_fp16_static_compact_ln_sim.onnx")

PROFILE_OVERRIDES: dict[str, list[str]] = {
    # Conservative first retry for our pre-simplified ONNX. Keep Samsung conversion/compile
    # behavior otherwise close to SDK Service defaults.
    "safe": [
        "--onnx_simplify",
        "false",
        "--input_dtype",
        "float32",
        "--output_dtype",
        "float32",
        "--graph_opt",
        "none",
        "--profile_batchsize",
        "1",
        "--target",
        "NPU",
    ],
    # Isolation profile if quantizer/profiling fails. Useful to prove ONNX->SNC/compile first.
    "no-quant": [
        "--onnx_simplify",
        "false",
        "--do_quantize",
        "false",
        "--input_dtype",
        "float32",
        "--output_dtype",
        "float32",
        "--graph_opt",
        "none",
        "--profile_batchsize",
        "1",
        "--target",
        "NPU",
    ],
    # Baseline close to documented defaults except simplification remains disabled because the
    # upload candidate is already simplified with Whisper-specific safeguards.
    "baseline-no-simplify": ["--onnx_simplify", "false"],
}


def repo_path(path: str | Path) -> Path:
    return Path(path).expanduser()


def load_project_config(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def comma_shape_to_list(shape: str | Sequence[int]) -> list[int]:
    if isinstance(shape, str):
        return [int(part.strip()) for part in shape.split(",") if part.strip()]
    return [int(part) for part in shape]


def workspace_config_path(workspace: Path) -> Path:
    return workspace / f"{workspace.name}.yaml"


def link_or_copy(src: Path, dst: Path, mode: str, overwrite: bool) -> str:
    src = src.resolve()
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        try:
            if dst.resolve() == src:
                return "already-present"
        except OSError:
            pass
        if not overwrite:
            return "already-present"
        dst.unlink()

    if mode == "none":
        return "skipped"
    if mode == "copy":
        shutil.copy2(src, dst)
        return "copied"
    if mode == "symlink":
        try:
            dst.symlink_to(src)
            return "symlinked"
        except OSError:
            shutil.copy2(src, dst)
            return "copied-fallback"

    # hardlink default: avoids a second 1.2GB file when workspace is on same volume.
    try:
        os.link(src, dst)
        return "hardlinked"
    except OSError:
        shutil.copy2(src, dst)
        return "copied-fallback"


def write_workspace_yaml(
    path: Path,
    *,
    device: str,
    input_name: str,
    input_shape: list[int],
    overwrite: bool,
) -> bool:
    if path.exists() and not overwrite:
        return False
    shape_inline = ", ".join(str(dim) for dim in input_shape)
    text = f"""# Generated by tools/samsung_eais_cli.py.
# Samsung docs: paths in this file should be relative to the model workspace.
general:
  device: {device}
  mode: legacy
  legacy_config_path: Config/legacy_config.yaml

database_gen:
  database_spec: Config/DATA/dbgen_spec.yaml

converter:
  # The ONNX is already prepared by this repo; keep Samsung from re-running onnxsim.
  onnx_simplify: false
  optimize: true
  do_quantize: true
  quantize_type: asymm
  activation_bitwidth: 8
  bw_kernel: 8
  calibration_method: percentile
  profile_batchsize: 1
  input_dtype: float32
  output_dtype: float32
  graph_opt: none
  target: NPU
  data_format: channel_first
  snc_converter: true
  test_vector_gen: false
  tv_input: Config/DATA/database.h5
  use_randomdb: true
  userdb: Config/DATA/database.txt

compiler:
  mode: tuning_mode
  compiler: NPU
  multicore: false
  optimization: O2

simulator:
  data_format: channel_first
  use_randomdb: false
  userdb: Config/DATA/data.txt

profiler:
  device_id: NOT_USE
  ssh_bool: SSH_FALSE
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def write_dbgen_placeholder(path: Path, *, input_name: str, input_shape: list[int], overwrite: bool) -> bool:
    if path.exists() and not overwrite:
        return False
    shape_inline = ", ".join(str(dim) for dim in input_shape)
    text = f"""# Generated placeholder for Samsung `eais generation`.
# If `eais init` creates a different schema, keep Samsung's generated schema and copy
# these values into it instead of forcing this file.
inputs:
  - name: {input_name}
    shape: [{shape_inline}]
    dtype: float32
    data: random
    min: -1.0
    max: 1.0
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def write_readme(workspace: Path, *, model_file: str, config_file: str, device: str) -> None:
    text = f"""# Samsung EAIS CLI workspace

Generated from this repo for Samsung Exynos AI Studio CLI testing.

Model file: `{model_file}`
Config file: `{config_file}`
Device: `{device}`

Recommended first local conversion command:

```bash
eais conversion --w . --f {config_file} --onnx_simplify false --input_dtype float32 --output_dtype float32 --graph_opt none --target NPU
```

If quantization/profiling fails, isolate converter/compile first:

```bash
eais conversion --w . --f {config_file} --onnx_simplify false --do_quantize false --input_dtype float32 --output_dtype float32 --graph_opt none --target NPU
```

Use `just eais-command conversion` from the repo root to print the same command.
"""
    (workspace / "README.md").write_text(text, encoding="utf-8", newline="\n")


def run_command(cmd: list[str], *, cwd: Path | None, execute: bool) -> int:
    printable = " ".join(f'"{part}"' if " " in part else part for part in cmd)
    if cwd:
        print(f"cwd: {cwd}")
    print(printable)
    if not execute:
        return 0
    return subprocess.call(cmd, cwd=str(cwd) if cwd else None)


def find_eais(binary: str) -> str | None:
    return shutil.which(binary)


def command_check(args: argparse.Namespace) -> int:
    found = find_eais(args.eais)
    if not found:
        print(f"EAIS CLI not found on PATH: {args.eais}")
        print("Install/run Samsung Exynos AI Studio CLI in Ubuntu/WSL2, then retry.")
        return 1
    print(f"EAIS CLI found: {found}")
    for cmd in ([args.eais, "package-info"], [args.eais, "--help"]):
        try:
            completed = subprocess.run(cmd, text=True, capture_output=True, timeout=60, check=False)
        except Exception as exc:  # pragma: no cover - environment dependent
            print(f"Could not run {' '.join(cmd)}: {exc}")
            continue
        print(f"\n$ {' '.join(cmd)}")
        output = (completed.stdout or completed.stderr).strip()
        print(output[:4000] if output else f"exit code {completed.returncode}")
    return 0


def command_workspace(args: argparse.Namespace) -> int:
    project = load_project_config(repo_path(args.project_config))
    model = repo_path(args.model or project.get("samsung_upload_model") or DEFAULT_MODEL)
    workspace = repo_path(args.workspace)
    device = args.device
    input_name = args.input_name or project.get("input_name") or "input_features"
    input_shape = comma_shape_to_list(args.input_shape or project.get("input_shape") or [1, 128, 3000])

    if not model.is_file():
        print(f"model not found: {model}", file=sys.stderr)
        return 1

    workspace.mkdir(parents=True, exist_ok=True)
    model_dst = workspace / "model.onnx"
    action = link_or_copy(model, model_dst, args.link, args.overwrite)
    cfg_path = workspace_config_path(workspace)
    wrote_cfg = write_workspace_yaml(
        cfg_path,
        device=device,
        input_name=input_name,
        input_shape=input_shape,
        overwrite=args.overwrite_config,
    )
    dbgen = workspace / "Config" / "DATA" / "dbgen_spec.yaml"
    wrote_dbgen = write_dbgen_placeholder(
        dbgen, input_name=input_name, input_shape=input_shape, overwrite=args.overwrite_config
    )
    write_readme(workspace, model_file=model_dst.name, config_file=cfg_path.name, device=device)

    print(f"workspace: {workspace}")
    print(f"model: {action} {model} -> {model_dst}")
    print(f"config: {'wrote' if wrote_cfg else 'kept'} {cfg_path}")
    print(f"dbgen: {'wrote' if wrote_dbgen else 'kept'} {dbgen}")
    print("Next:")
    print(f"  just eais-command conversion {workspace} safe")
    print(f"  just eais-conversion {workspace} safe")
    return 0


def build_eais_command(args: argparse.Namespace) -> list[str]:
    workspace = repo_path(args.workspace)
    if args.command == "init":
        return [args.eais, "init", "--w", workspace.as_posix()]
    config = args.config or workspace_config_path(workspace).name
    cmd = [args.eais, args.command, "--w", workspace.as_posix(), "--f", config]
    if args.command == "conversion":
        cmd += PROFILE_OVERRIDES.get(args.profile, [])
    return cmd


def command_run(args: argparse.Namespace) -> int:
    if args.execute and not find_eais(args.eais):
        print(f"EAIS CLI not found on PATH: {args.eais}", file=sys.stderr)
        return 1
    cmd = build_eais_command(args)
    return run_command(cmd, cwd=None, execute=args.execute)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="subcommand", required=True)

    check = sub.add_parser("check", help="Check whether Samsung `eais` is available.")
    check.add_argument("--eais", default="eais")
    check.set_defaults(func=command_check)

    workspace = sub.add_parser("workspace", help="Create/update a local EAIS CLI workspace.")
    workspace.add_argument("--project-config", default=str(DEFAULT_CONFIG))
    workspace.add_argument("--model", default=None)
    workspace.add_argument("--workspace", default=str(DEFAULT_WORKSPACE))
    workspace.add_argument("--device", default="Gen-8")
    workspace.add_argument("--input-name", default=None)
    workspace.add_argument("--input-shape", default=None)
    workspace.add_argument("--link", choices=["hardlink", "copy", "symlink", "none"], default="hardlink")
    workspace.add_argument("--overwrite", action="store_true", help="Replace existing linked/copied model.")
    workspace.add_argument("--overwrite-config", action="store_true", help="Replace existing YAML files.")
    workspace.set_defaults(func=command_workspace)

    run = sub.add_parser("run", help="Print or execute an `eais` command.")
    run.add_argument("command", choices=["init", "generation", "conversion", "compile", "profiling"])
    run.add_argument("--workspace", default=str(DEFAULT_WORKSPACE))
    run.add_argument("--config", default=None)
    run.add_argument("--profile", choices=sorted(PROFILE_OVERRIDES), default="safe")
    run.add_argument("--eais", default="eais")
    run.add_argument("--execute", action="store_true")
    run.set_defaults(func=command_run)

    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
