#!/usr/bin/env python3
"""Cross-platform workspace helpers used by the justfile.

Keep shell-specific filesystem operations out of recipes so the same commands work
from Windows cmd/PowerShell, macOS, and Linux shells.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path


STANDARD_DIRS = [
    "input/whisper-large-v3-turbo",
    "input/hf",
    "output/onnx",
    "output/static",
    "output/simplified",
    "output/quantized",
    "output/samsung",
    "output/final",
    "output/reports",
    "configs",
    "docs",
]


def human_size(size: int) -> str:
    value = float(size)
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if value < 1024 or unit == "TB":
            return f"{value:.1f} {unit}" if unit != "B" else f"{int(value)} B"
        value /= 1024
    return f"{value:.1f} TB"


def command_setup(args: argparse.Namespace) -> int:
    dirs = args.dirs or STANDARD_DIRS
    for item in dirs:
        Path(item).mkdir(parents=True, exist_ok=True)
    return 0


def command_require_file(args: argparse.Namespace) -> int:
    path = Path(args.path)
    if not path.is_file():
        raise SystemExit(f"Missing file: {path}")
    return 0


def command_ensure_parent(args: argparse.Namespace) -> int:
    Path(args.path).parent.mkdir(parents=True, exist_ok=True)
    return 0


def command_ls_size(args: argparse.Namespace) -> int:
    path = Path(args.path)
    if not path.exists():
        raise SystemExit(f"Missing path: {path}")
    print(f"{human_size(path.stat().st_size):>10}  {path}")
    return 0


def command_remove(args: argparse.Namespace) -> int:
    for item in args.paths:
        path = Path(item)
        if path.is_dir() and not path.is_symlink():
            shutil.rmtree(path, ignore_errors=True)
        else:
            path.unlink(missing_ok=True)
    return 0


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def command_upload_list(args: argparse.Namespace) -> int:
    print("Upload/convert this first in Samsung SDK Service:")
    print(f"  {args.static_model}")
    print()
    print("Keep tokenizer/preprocessor files with your app/runtime as needed; they are not NPU binaries:")
    print(f"  {args.input_dir}/config.json")
    print("  tokenizer.json tokenizer_config.json generation_config.json")
    print("  preprocessor_config.json special_tokens_map.json normalizer.json vocab.json merges.txt added_tokens.json")
    return 0


def command_publish_final(args: argparse.Namespace) -> int:
    source = Path(args.model)
    if not source.is_file():
        raise SystemExit(f"Missing model: {source}")

    final_dir = Path(args.final_dir)
    final_dir.mkdir(parents=True, exist_ok=True)

    # Keep this folder unambiguous: exactly one ONNX upload target.
    for existing in final_dir.glob("*.onnx"):
        existing.unlink()

    final_model = final_dir / args.name
    if args.copy:
        shutil.copy2(source, final_model)
        method = "copied"
    else:
        try:
            os.link(source, final_model)
            method = "hardlinked"
        except OSError:
            shutil.copy2(source, final_model)
            method = "copied-fallback"

    digest = sha256_file(final_model)
    manifest = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "purpose": "single Samsung SDK Service upload folder",
        "upload_file": final_model.name,
        "source_model": str(source),
        "size_bytes": final_model.stat().st_size,
        "sha256": digest,
        "input_name": args.input_name,
        "input_shape": args.input_shape,
        "output_name": args.output_name,
        "output_shape": args.output_shape,
        "notes": [
            "Upload only the ONNX file in this folder for Samsung conversion.",
            "This folder is regenerated by `just final-samsung` / `just prepare-samsung`.",
            "Tokenizer and preprocessor files stay with the app/runtime; they are not NPU binaries.",
        ],
    }
    (final_dir / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (final_dir / "README.txt").write_text(
        "FINAL SAMSUNG UPLOAD FOLDER\n"
        "===========================\n\n"
        "Upload this file to Samsung SDK Service / AI Studio conversion:\n\n"
        f"  {final_model.name}\n\n"
        f"SHA256:\n  {digest}\n\n"
        f"Input:  {args.input_name} {args.input_shape}\n"
        f"Output: {args.output_name} {args.output_shape}\n\n"
        "Do not upload older models from output/onnx, output/static, or output/simplified.\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"Final Samsung upload folder: {final_dir}")
    print(f"  {method}: {source} -> {final_model}")
    print(f"  sha256: {digest}")
    print("Upload this one file:")
    print(f"  {final_model}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Cross-platform workspace helper commands.")
    sub = parser.add_subparsers(dest="command", required=True)

    setup = sub.add_parser("setup", help="Create standard workspace directories.")
    setup.add_argument("dirs", nargs="*")
    setup.set_defaults(func=command_setup)

    require_file = sub.add_parser("require-file", help="Fail if a file does not exist.")
    require_file.add_argument("path")
    require_file.set_defaults(func=command_require_file)

    ensure_parent = sub.add_parser("ensure-parent", help="Create a path's parent directory.")
    ensure_parent.add_argument("path")
    ensure_parent.set_defaults(func=command_ensure_parent)

    ls_size = sub.add_parser("ls-size", help="Print a compact file size line.")
    ls_size.add_argument("path")
    ls_size.set_defaults(func=command_ls_size)

    remove = sub.add_parser("remove", help="Remove files/directories if they exist.")
    remove.add_argument("paths", nargs="+")
    remove.set_defaults(func=command_remove)

    upload_list = sub.add_parser("upload-list", help="Print Samsung SDK upload guidance.")
    upload_list.add_argument("static_model")
    upload_list.add_argument("--input-dir", default="input/whisper-large-v3-turbo")
    upload_list.set_defaults(func=command_upload_list)

    publish_final = sub.add_parser("publish-final", help="Create the single final upload folder.")
    publish_final.add_argument("model")
    publish_final.add_argument("--final-dir", default="output/final")
    publish_final.add_argument("--name", default="SAMSUNG_UPLOAD_WHISPER_ENCODER.onnx")
    publish_final.add_argument("--copy", action="store_true", help="Copy instead of hardlinking when possible.")
    publish_final.add_argument("--input-name", default="input_features")
    publish_final.add_argument("--input-shape", default="[1, 128, 3000]")
    publish_final.add_argument("--output-name", default="last_hidden_state")
    publish_final.add_argument("--output-shape", default="[1, 1500, 1280]")
    publish_final.set_defaults(func=command_publish_final)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
